apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: valay
profiles:
  - name: set-trigger-values
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          "{{.TRIGGER_PROJECT_NAME}}":
            image:
              tag: "{{.TRIGGER_COMMIT_SHA}}"
  - name: production
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: gke_valay-prod_us-central1-a_valay
      - op: replace
        path: /deploy/helm/flags
        value:
          install: [ "--post-renderer=./charts/valay/kustomizations/production/us-central/render.sh" ]
          upgrade: [ "--post-renderer=./charts/valay/kustomizations/production/us-central/render.sh" ]
      - op: replace
        path: /deploy/helm/releases/0/name
        value: stable
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/-
        value: charts/valay/values-production.yaml
      - op: replace
        path: /build/local/push
        value: true
  - name: test
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: gke_valay-176920_us-east1-b_valay
      - op: replace
        path: /deploy/helm/flags
        value:
          install: [ "--post-renderer=./charts/valay/kustomizations/test/us-east/render.sh" ]
          upgrade: [ "--post-renderer=./charts/valay/kustomizations/test/us-east/render.sh" ]
      - op: replace
        path: /deploy/helm/releases/0/name
        value: beta
      - op: add
        path: /deploy/helm/releases/0/valuesFiles/-
        value: charts/valay/values-test.yaml
      - op: replace
        path: /build/local/push
        value: true
  - name: minikube
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: minikube
  - name: run-delete
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          runScripts:
            delete: true
          image:
            tag: ""
          "valay-authentication":
            image:
              tag: ""
          "valay-user":
            image:
              tag: ""
          "valay-web":
            image:
              tag: ""
          "valay-notification":
            image:
              tag: ""
  - name: run-migrations
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          runScripts:
            migrations: true
          image:
            tag: ""
          "valay-authentication":
            image:
              tag: ""
          "valay-user":
            image:
              tag: ""
          "valay-web":
            image:
              tag: ""
          "valay-notification":
            image:
              tag: ""
  - name: remove-tags
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          image:
            tag: ""
          "valay-authentication":
            image:
              tag: ""
          "valay-user":
            image:
              tag: ""
          "valay-web":
            image:
              tag: ""
          "valay-notification":
            image:
              tag: ""
  - name: add-artifacts
    patches:
      - op: add
        path: /deploy/helm/releases/0/artifactOverrides
        value:
          image:
            repository: valay-setup
          "valay-web":
            image:
              repository: valay-web
          "valay-authentication":
            image:
              repository: valay-authentication
          "valay-user":
            image:
              repository: valay-user
          "valay-notification":
            image:
              repository: valay-notification
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: valay-web
      context: ../valay/web
      docker:
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
    - image: valay-authentication
      context: ../valay/authentication
      docker:
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
    - image: valay-setup
      context: ../valay/setup
      docker:
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
    - image: valay-user
      context: ../valay/user
      docker:
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
    - image: valay-notification
      context: ../valay/notification
      docker:
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
test:
  - image: valay-web
    context: ../valay/web/server
    custom:
      - command: node_modules/.bin/jest --runInBand --silent
  - image: valay-authentication
    context: ../valay/authentication/server
    custom:
      - command: node_modules/.bin/jest --runInBand --silent
  - image: valay-user
    context: ../valay/user/server
    custom:
      - command: node_modules/.bin/jest --runInBand --silent
  - image: valay-notification
    context: ../valay/notification/server
    custom:
      - command: node_modules/.bin/jest --runInBand --silent
deploy:
  statusCheckDeadlineSeconds: 300
  kubeContext: docker-desktop
  logs:
    prefix: podAndContainer
  helm:
    flags:
      install: [ "--post-renderer=./charts/valay/kustomizations/dev/render.sh" ]
      upgrade: [ "--post-renderer=./charts/valay/kustomizations/dev/render.sh" ]
    releases:
      - name: alpha
        chartPath: charts/valay
        namespace: valay
        valuesFiles:
          - charts/valay/values.yaml
        setValueTemplates: {}
        artifactOverrides: {}
portForward:
  - resourceType: service
    resourceName: web
    namespace: valay-web
    port: 10001
    localPort: 8080
    address: 0.0.0.0
  - resourceType: service
    resourceName: alpha-mongo-main
    namespace: valay
    port: 27017
    localPort: 27017
    address: 0.0.0.0
  - resourceType: service
    resourceName: alpha-mongo-sessions
    namespace: valay
    port: 27017
    localPort: 27018
    address: 0.0.0.0
  - resourceType: service
    resourceName: alpha-mongo-migrations
    namespace: valay
    port: 27017
    localPort: 27019
    address: 0.0.0.0
