apiVersion: v1
kind: Service
metadata:
  name: {{ include "valay-payment.name" . }}
  namespace: {{ include "valay-payment.namespaceName" . }}
  labels:
    {{- include "valay-payment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      appProtocol: http
    - port: {{ .Values.serviceGrpc.port }}
      name: grpc
      protocol: TCP
      appProtocol: grpc
  selector:
    {{- include "valay-payment.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
