image:
  repository: setup
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets:
  - name: docker-registry-auth
nameOverride: setup
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

runScripts:
  delete: false
  migrations: false

mongo-main:
  enabled: true
  image:
    repository: bitnami/mongodb
    tag: 4.4.8-debian-10-r0
  service:
    port: 27017
  auth:
    enabled: false
  persistence:
    enabled: false
  metrics:
    enabled: false

mongo-migrations:
  enabled: true
  image:
    repository: bitnami/mongodb
    tag: 4.4.8-debian-10-r0
  service:
    port: 27017
  auth:
    enabled: false
  persistence:
    enabled: false
  metrics:
    enabled: false

mongo-sessions:
  enabled: true
  image:
    repository: bitnami/mongodb
    tag: 4.4.8-debian-10-r0
  service:
    port: 27017
  auth:
    enabled: false
  persistence:
    enabled: false
  metrics:
    enabled: false
  