image:
  repository: docker.io/valayorg/setup
  pullPolicy: Always
  tag: test
nodeSelector:
  "cloud.google.com/gke-nodepool": app
tolerations:
  - key: "app/app-reserved"
    operator: Exists
    effect: NoSchedule

mongo-main:
  enabled: false

mongo-migrations:
  enabled: false

mongo-sessions:
  enabled: false

valay-authentication:
  image:
    repository: docker.io/valayorg/authentication
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

valay-notification:
  image:
    repository: docker.io/valayorg/notification
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

valay-user:
  image:
    repository: docker.io/valayorg/user
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

valay-web:
  image:
    repository: docker.io/valayorg/web
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M
