image:
  repository: docker.io/valayorg/setup
  tag: 1.0.0
nodeSelector:
  "cloud.google.com/gke-nodepool": app
tolerations:
  - key: "app/app-reserved"
    operator: Exists
    effect: NoSchedule

mongo-main:
  enabled: false

mongo-migrations:
  enabled: false

mongo-sessions:
  enabled: false

valay-authentication:
  image:
    repository: docker.io/valayorg/authentication
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M

valay-notification:
  image:
    repository: docker.io/valayorg/notification
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M

valay-user:
  image:
    repository: docker.io/valayorg/user
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M

valay-web:
  image:
    repository: docker.io/valayorg/web
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M
