apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
generatorOptions:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"

patches:
  - path: migrations-job.yaml
    target:
      kind: Job
      name: migrations
      namespace: valay-setup

  - path: admin-web-deployment.yaml
    target:
      kind: Deployment
      name: admin-web
      namespace: valay-admin-web

  - path: authentication-deployment.yaml
    target:
      kind: Deployment
      name: authentication
      namespace: valay-authentication

  - path: notification-deployment.yaml
    target:
      kind: Deployment
      name: notification
      namespace: valay-notification

  - path: payment-deployment.yaml
    target:
      kind: Deployment
      name: payment
      namespace: valay-payment

  - path: place-deployment.yaml
    target:
      kind: Deployment
      name: place
      namespace: valay-place

  - path: user-deployment.yaml
    target:
      kind: Deployment
      name: user
      namespace: valay-user

  - path: web-deployment.yaml
    target:
      kind: Deployment
      name: web
      namespace: valay-web

secretGenerator:
  - name: docker-registry-auth
    namespace: valay-setup
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: storage-service-account
    namespace: valay-setup
    files:
      - files/storage-service-account-key.json

  - name: config
    namespace: valay-setup
    envs:
      - env/config.env

  - name: mongo-main
    namespace: valay-setup
    envs:
      - env/mongo-main.env

  - name: mongo-migrations
    namespace: valay-setup
    envs:
      - env/mongo-migrations.env

  - name: mongo-sessions
    namespace: valay-setup
    envs:
      - env/mongo-sessions.env

  - name: cloudinary
    namespace: valay-setup
    envs:
      - env/cloudinary.env

  - name: google
    namespace: valay-setup
    envs:
      - env/google.env
  #-----------------------------------------------------------------
  - name: docker-registry-auth
    namespace: valay-admin-web
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: config
    namespace: valay-admin-web
    envs:
      - env/config.env

  - name: server-http
    namespace: valay-admin-web
    envs:
      - env/server-http.env
  #-----------------------------------------------------------------
  - name: docker-registry-auth
    namespace: valay-authentication
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: config
    namespace: valay-authentication
    envs:
      - env/config.env

  - name: mongo-main
    namespace: valay-authentication
    envs:
      - env/mongo-main.env

  - name: mongo-sessions
    namespace: valay-authentication
    envs:
      - env/mongo-sessions.env

  - name: server-http
    namespace: valay-authentication
    envs:
      - env/server-http.env

  - name: server-grpc
    namespace: valay-authentication
    envs:
      - env/server-grpc.env

  - name: jwt
    namespace: valay-authentication
    envs:
      - env/jwt.env
  #-----------------------------------------------------------------
  - name: docker-registry-auth
    namespace: valay-notification
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: config
    namespace: valay-notification
    envs:
      - env/config.env

  - name: mongo-main
    namespace: valay-notification
    envs:
      - env/mongo-main.env

  - name: google
    namespace: valay-notification
    envs:
      - env/google.env

  - name: server-http
    namespace: valay-notification
    envs:
      - env/server-http.env

  - name: server-grpc
    namespace: valay-notification
    envs:
      - env/server-grpc.env

  - name: sendgrid
    namespace: valay-notification
    envs:
      - env/sendgrid.env
  #-----------------------------------------------------------------
  - name: docker-registry-auth
    namespace: valay-payment
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: config
    namespace: valay-payment
    envs:
      - env/config.env

  - name: mongo-main
    namespace: valay-payment
    envs:
      - env/mongo-main.env

  - name: server-http
    namespace: valay-payment
    envs:
      - env/server-http.env

  - name: server-grpc
    namespace: valay-payment
    envs:
      - env/server-grpc.env

  - name: stripe
    namespace: valay-payment
    envs:
      - env/stripe.env
  #-----------------------------------------------------------------
  - name: docker-registry-auth
    namespace: valay-place
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: storage-service-account
    namespace: valay-place
    files:
      - files/storage-service-account-key.json

  - name: config
    namespace: valay-place
    envs:
      - env/config.env

  - name: mongo-main
    namespace: valay-place
    envs:
      - env/mongo-main.env

  - name: server-http
    namespace: valay-place
    envs:
      - env/server-http.env

  - name: server-grpc
    namespace: valay-place
    envs:
      - env/server-grpc.env

  - name: cloudinary
    namespace: valay-place
    envs:
      - env/cloudinary.env

  - name: google
    namespace: valay-place
    envs:
      - env/google.env
  #-----------------------------------------------------------------
  - name: docker-registry-auth
    namespace: valay-user
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: storage-service-account
    namespace: valay-user
    files:
      - files/storage-service-account-key.json

  - name: config
    namespace: valay-user
    envs:
      - env/config.env

  - name: mongo-main
    namespace: valay-user
    envs:
      - env/mongo-main.env

  - name: server-http
    namespace: valay-user
    envs:
      - env/server-http.env

  - name: server-grpc
    namespace: valay-user
    envs:
      - env/server-grpc.env

  - name: cloudinary
    namespace: valay-user
    envs:
      - env/cloudinary.env

  - name: google
    namespace: valay-user
    envs:
      - env/google.env
  #-----------------------------------------------------------------
  - name: docker-registry-auth
    namespace: valay-web
    files:
      - files/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

  - name: storage-service-account
    namespace: valay-web
    files:
      - files/storage-service-account-key.json

  - name: config
    namespace: valay-web
    envs:
      - env/config.env

  - name: google
    namespace: valay-web
    envs:
      - env/google.env

  - name: server-http
    namespace: valay-web
    envs:
      - env/server-http.env

  - name: server-grpc
    namespace: valay-web
    envs:
      - env/server-grpc.env

  - name: jwt
    namespace: valay-web
    envs:
      - env/jwt.env
