apiVersion: apps/v1
kind: Deployment
metadata:
  name: does-not-matter
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: APP_DEV_LOCAL
              value: "1"

