name: release
on:
  push:
    branches:
      - master
    paths:
      - charts/valay/Chart.yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: ${{secrets.GITHUB_TOKEN}}
